-- =============================================
-- Author:		VALENTINA MOLINA
-- Create date: 02/12/2021
-- Description:	Procedimiento almacenado utilizado para la actualización del LT STANDAR en el consolidado.
-- EXEC NS_spActualizarLTSTD
-- =============================================
CREATE PROCEDURE [dbo].[NS_spActualizarLTSTD_2]
	
AS
BEGIN


--ACTUALIZAR EN LA TABLA ORIGINAL DE LEAD TIME LOS ID PARA CRUZAR CON LA TABLA DE CONSOLIDADO

UPDATE LT SET [idCountry]=CO.Pkid,[idOrigin_Country]=OC.Pkid
--SELECT CO.Pkid,LT.COUNTRY,OC.Pkid,LT.ORIGIN_COUNTRY,LT.AIR,LT.ROAD,LT.OCEAN --LT.COUNTRY,LT.ORIGIN_COUNTRY,LT.AIR 
FROM [maestros].[LEAD_TIME] LT 
LEFT JOIN maestros.NS_tblOrigin_Country OC ON LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Codigo)) OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.DescripcionEspanol)) OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion1))  OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion2)) OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion3)) OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion4)) OR LTRIM(RTRIM(LT.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion5))								
LEFT JOIN maestros.NS_tblCountry CO ON LTRIM(RTRIM(LT.COUNTRY)) = LTRIM(RTRIM(CO.Codigo)) OR LTRIM(RTRIM(LT.COUNTRY)) = LTRIM(RTRIM(CO.DescripcionEspanol))
--WHERE OC.Pkid IS NULL

--BORRAR EL CAMPO LT_STD SI TRAE ALGO DESDE LA DATA
--UPDATE [comex].[NS_tblConsolidado] SET LT_STD='' WHERE LT_STD=''
--SELECT * FROM [comex].[NS_tblConsolidado] WHERE AÑO=2022 AND MODAL IN ('AIR','AEREO','AÉREO') 

--ACTUALIZAR EL LT STD EN EL CONSOLIDADO


--ACTUALIZAR MODAL AEREO
UPDATE C SET LT_STD=LT.AIR
--SELECT C.Pkid,CO.Pkid,C.COUNTRY,OC.Pkid,C.ORIGIN_COUNTRY,C.MODAL,LT.COUNTRY,LT.ORIGIN_COUNTRY,LT.AIR 
--SELECT DISTINCT  CO.Pkid,C.COUNTRY,OC.Pkid,C.ORIGIN_COUNTRY,OC.DescripcionEspanol,C.MODAL
FROM [comex].[NS_tblConsolidado] C 
LEFT JOIN [maestros].[NS_tblCountry] CO ON LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.Codigo)) OR LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.DescripcionEspanol))
LEFT JOIN maestros.NS_tblOrigin_Country OC ON LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Codigo)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.DescripcionEspanol)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion1))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion2)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion3)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion4)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion5))		
LEFT JOIN [maestros].[LEAD_TIME] LT ON CO.Pkid=LT.idCountry AND OC.Pkid=LT.idOrigin_Country
WHERE C.MODAL IN ('AIR','AEREO','AÉREO') AND C.AÑO=LT.AÑO AND C.COMPAÑIA=LT.COMPAÑIA  --AND C.AÑOMES<=MONTH(LT.[INI_VIGENCIA])
--WHERE LT.COUNTRY IS NULL ORDER BY CO.Pkid,OC.Pkid
--WHERE CO.Pkid IN (1,2,3) AND LT.COUNTRY IS NULL
--AND C.PKID IN ('4701','6120','6122')  --->REGISTROS SIN LT
--ORDER BY C.PKID,CO.Pkid,C.COUNTRY,OC.Pkid,C.ORIGIN_COUNTRY,C.MODAL

--ACTUALIZAR MODAL MARITIMO
UPDATE C SET LT_STD=LT.OCEAN
FROM [comex].[NS_tblConsolidado] C 
LEFT JOIN [maestros].[NS_tblCountry] CO ON LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.Codigo)) OR LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.DescripcionEspanol))
LEFT JOIN maestros.NS_tblOrigin_Country OC ON LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Codigo)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.DescripcionEspanol)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion1))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion2)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion3)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion4)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion5))		
LEFT JOIN [maestros].[LEAD_TIME] LT ON CO.Pkid=LT.idCountry AND OC.Pkid=LT.idOrigin_Country
WHERE C.MODAL IN ('SEA','MARITIMO','MARÍTIMO','OCEAN') AND C.AÑO=LT.AÑO AND C.COMPAÑIA=LT.COMPAÑIA


--ACTUALIZAR MODAL TERRESTRE
UPDATE C SET LT_STD=LT.ROAD
FROM [comex].[NS_tblConsolidado] C 
LEFT JOIN [maestros].[NS_tblCountry] CO ON LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.Codigo)) OR LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.DescripcionEspanol))
LEFT JOIN maestros.NS_tblOrigin_Country OC ON LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Codigo)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.DescripcionEspanol)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion1))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion2)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion3)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion4)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion5))		
LEFT JOIN [maestros].[LEAD_TIME] LT ON CO.Pkid=LT.idCountry AND OC.Pkid=LT.idOrigin_Country
WHERE C.MODAL IN ('ROAD','TERRESTRE','RODOVIÁRIO') AND C.AÑO=LT.AÑO AND C.COMPAÑIA=LT.COMPAÑIA




----ORIGIN_COUNTRY QUE NO TIENEN LT STD EN EL ARCHIVO
/*
SELECT DISTINCT  CO.Pkid,C.COUNTRY,OC.Pkid,C.ORIGIN_COUNTRY,OC.DescripcionEspanol,C.MODAL,LT.AIR,LT.OCEAN,LT.ROAD,C.INCOTERM
FROM [comex].[NS_tblConsolidado] C 
LEFT JOIN [maestros].[NS_tblCountry] CO ON LTRIM(RTRIM(C.COUNTRY)) = LTRIM(RTRIM(CO.Codigo)) 
LEFT JOIN maestros.NS_tblOrigin_Country OC ON LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Codigo)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.DescripcionEspanol)) OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion1))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion2))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion3))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion4))  OR LTRIM(RTRIM(C.ORIGIN_COUNTRY)) = LTRIM(RTRIM(OC.Homologacion5))		
LEFT JOIN [maestros].[LEAD_TIME] LT ON CO.Pkid=LT.idCountry AND OC.Pkid=LT.idOrigin_Country
WHERE CO.Pkid IN (1,2,3) AND LT.COUNTRY IS NULL 
ORDER BY CO.Pkid,OC.Pkid
*/
-----------------------------

	
END

GO

