CREATE TABLE [temp].[NS_tblPeru_Temp] (
    [AÑO]                        NVARCHAR (250) NULL,
    [MES]                        NVARCHAR (250) NULL,
    [COMPAÑIA]                   NVARCHAR (250) NULL,
    [Country]                    NVARCHAR (250) NULL,
    [Shipment_Reference]         NVARCHAR (250) NULL,
    [Supplier]                   NVARCHAR (350) NULL,
    [Incoterm]                   NVARCHAR (250) NULL,
    [Product_Cost]               NVARCHAR (250) NULL,
    [Cnt_20_QTY]                 NVARCHAR (250) NULL,
    [Cnt_40_QTY]                 NVARCHAR (250) NULL,
    [OriginRegion]               NVARCHAR (250) NULL,
    [Origin_Country]             NVARCHAR (250) NULL,
    [Origin_City_Pick_Up]        NVARCHAR (250) NULL,
    [Origin_port_airport_name]   NVARCHAR (250) NULL,
    [Dest_Country]               NVARCHAR (250) NULL,
    [M3]                         NVARCHAR (250) NULL,
    [Freight_forwarder]          NVARCHAR (250) NULL,
    [Type]                       NVARCHAR (250) NULL,
    [Descripción_Modal]          NVARCHAR (250) NULL,
    [Dest_port_airport_name]     NVARCHAR (250) NULL,
    [Dest_city]                  NVARCHAR (250) NULL,
    [KG]                         NVARCHAR (250) NULL,
    [Freight_value]              NVARCHAR (250) NULL,
    [Import_Duty]                NVARCHAR (250) NULL,
    [Pick_up_date]               NVARCHAR (250) NULL,
    [Ship_date]                  NVARCHAR (250) NULL,
    [Arrival_date]               NVARCHAR (250) NULL,
    [Numeración]                 NVARCHAR (250) NULL,
    [Custom_clearance_date]      NVARCHAR (250) NULL,
    [Avon_receipt]               NVARCHAR (250) NULL,
    [PO]                         NVARCHAR (350) NULL,
    [Qty_PO]                     NVARCHAR (250) NULL,
    [Product_category]           NVARCHAR (250) NULL,
    [Dangerous_goods]            NVARCHAR (250) NULL,
    [Spot_shipment]              NVARCHAR (250) NULL,
    [International_insurance]    NVARCHAR (250) NULL,
    [Customs_expenses]           NVARCHAR (250) NULL,
    [Inland_freight_dest]        NVARCHAR (250) NULL,
    [Inland_transport_company]   NVARCHAR (250) NULL,
    [Doc_Transporte]             NVARCHAR (250) NULL,
    [Declaración]                NVARCHAR (250) NULL,
    [Referencia]                 NVARCHAR (250) NULL,
    [ISD_Factura_Comercial]      NVARCHAR (250) NULL,
    [ISD_Gastos_Logisticos]      NVARCHAR (250) NULL,
    [Facturas]                   NVARCHAR (250) NULL,
    [Fecha_Liquidación]          NVARCHAR (250) NULL,
    [Tasa_de_Cambio_Liquidación] NVARCHAR (250) NULL,
    [LT_STD]                     NVARCHAR (250) NULL,
    [PALLETS]                    NVARCHAR (250) NULL,
    [FECHA_DISPONIBILIZACION]    NVARCHAR (250) NULL,
    [FECHA_FACTURA]              NVARCHAR (250) NULL
) ON [DATOSTEMP];


GO

