CREATE TABLE [temp].[NS_tblColombia_Temp] (
    [AÑO]                      NVARCHAR (250) NULL,
    [MONTH]                    NVARCHAR (250) NULL,
    [COMPAÑIA]                 NVARCHAR (250) NULL,
    [COUNTRY]                  NVARCHAR (250) NULL,
    [SHIPMENT_REFERENCE]       NVARCHAR (250) NULL,
    [EMBARQUE]                 NVARCHAR (250) NULL,
    [BL]                       NVARCHAR (250) NULL,
    [ORIGIN_REGION]            NVARCHAR (250) NULL,
    [ORIGIN_COUNTRY]           NVARCHAR (250) NULL,
    [ORIGIN_CITY_PICK_UP]      NVARCHAR (250) NULL,
    [ORIGIN_PORT_AIRPORT_NAME] NVARCHAR (250) NULL,
    [DEST_COUNTRY]             NVARCHAR (250) NULL,
    [DESTINATION_CITY]         NVARCHAR (250) NULL,
    [DEST_PORT_AIRPORT_NAME]   NVARCHAR (250) NULL,
    [MODAL]                    NVARCHAR (250) NULL,
    [C_TYPE]                   NVARCHAR (250) NULL,
    [CNT_20_QTY]               NVARCHAR (250) NULL,
    [CNT_40_QTY]               NVARCHAR (250) NULL,
    [GROSS_WEIGHT]             NVARCHAR (250) NULL,
    [M3]                       NVARCHAR (250) NULL,
    [FREIGHT_FORWARDER]        NVARCHAR (250) NULL,
    [SUPPLIER]                 NVARCHAR (250) NULL,
    [INCOTERM]                 NVARCHAR (250) NULL,
    [PRODUCT_COST]             NVARCHAR (250) NULL,
    [FREIGHT_VALUE]            NVARCHAR (250) NULL,
    [IMPORT_DUTY]              NVARCHAR (250) NULL,
    [PICK_UP_DATE]             NVARCHAR (250) NULL,
    [SHIP_DATE]                NVARCHAR (250) NULL,
    [ARRIVAL_DATE]             NVARCHAR (250) NULL,
    [CUSTOM_CLEARANCE_DATE]    NVARCHAR (250) NULL,
    [AVON_RECEIPT]             NVARCHAR (250) NULL,
    [QTY_PO]                   NVARCHAR (250) NULL,
    [PRODUCT_CATEGORY]         NVARCHAR (250) NULL,
    [DANGEROUS_GOOD]           NVARCHAR (250) NULL,
    [SPOT_SHIPMENT]            NVARCHAR (250) NULL,
    [INTERNATIONAL_INSURANCE]  NVARCHAR (250) NULL,
    [CUSTOM_EXPENSES]          NVARCHAR (250) NULL,
    [INLAND_FREIGHT_DESP]      NVARCHAR (250) NULL,
    [INLAND_TRANSPORT_COMPANY] NVARCHAR (250) NULL,
    [LT_STD]                   NVARCHAR (250) NULL,
    [FECHA_RECEBTO]            NVARCHAR (250) NULL,
    [FACTURA]                  NVARCHAR (250) NULL,
    [FECHA_FACTURA]            NVARCHAR (250) NULL,
    [PALLETS]                  NVARCHAR (250) NULL,
    [OC]                       NVARCHAR (250) NULL
) ON [DATOSTEMP];


GO

