CREATE TABLE [temp].[NS_tblChile_Temp] (
    [Año]                            NVARCHAR (250) NULL,
    [Empresa]                        NVARCHAR (250) NULL,
    [Country]                        NVARCHAR (250) NULL,
    [Quarter]                        NVARCHAR (250) NULL,
    [Month]                          NVARCHAR (250) NULL,
    [SHIPMENT REFERENCE]             NVARCHAR (250) NULL,
    [Customs Broker]                 NVARCHAR (250) NULL,
    [ORIGIN REGION]                  NVARCHAR (250) NULL,
    [ORIGIN COUNTRY]                 NVARCHAR (250) NULL,
    [ORIGIN CITY PICK UP]            NVARCHAR (250) NULL,
    [ORIGIN PORT AIRPORT NAME]       NVARCHAR (250) NULL,
    [DEST COUNTRY]                   NVARCHAR (250) NULL,
    [DESTINATION CITY]               NVARCHAR (250) NULL,
    [DEST PORT AIRPORT NAME]         NVARCHAR (250) NULL,
    [MODAL]                          NVARCHAR (250) NULL,
    [C TYPE]                         NVARCHAR (250) NULL,
    [CNT 20 QTY]                     NVARCHAR (250) NULL,
    [CNT 40 QTY]                     NVARCHAR (250) NULL,
    [GROSS WEIGHT]                   NVARCHAR (250) NULL,
    [VOLUME]                         NVARCHAR (250) NULL,
    [FREIGHT FORWARDER]              NVARCHAR (250) NULL,
    [SUPPLIER]                       NVARCHAR (250) NULL,
    [INCOTERM]                       NVARCHAR (250) NULL,
    [Currency - Product Cost]        NVARCHAR (250) NULL,
    [Product Cost (USD)]             NVARCHAR (250) NULL,
    [FREIGHT VALUE]                  NVARCHAR (250) NULL,
    [IMPORT DUTY]                    NVARCHAR (250) NULL,
    [PICK UP DATE]                   NVARCHAR (250) NULL,
    [SHIP DATE]                      NVARCHAR (250) NULL,
    [ARRIVAL DATE]                   NVARCHAR (250) NULL,
    [CUSTOM CLEARANCE DATE]          NVARCHAR (250) NULL,
    [AVON RECEIPT]                   NVARCHAR (250) NULL,
    [QTY PO]                         NVARCHAR (250) NULL,
    [PRODUCT CATEGORY]               NVARCHAR (250) NULL,
    [DANGEROUS GOOD]                 NVARCHAR (250) NULL,
    [SPOT SHIPMENT]                  NVARCHAR (250) NULL,
    [INTERNATIONAL INSURANCE]        NVARCHAR (250) NULL,
    [CUSTOM EXPENSES]                NVARCHAR (250) NULL,
    [INLAND FREIGHT DESP]            NVARCHAR (250) NULL,
    [INLAND TRANSPORT COMPANY]       NVARCHAR (250) NULL,
    [Quantities]                     NVARCHAR (250) NULL,
    [UNIDAD DE MEDIDA]               NVARCHAR (250) NULL,
    [Total Logistics Spend W/duties] NVARCHAR (250) NULL
);


GO

