CREATE TABLE [maestros].[NS_tblPeru] (
    [Pkid]                       INT           IDENTITY (1, 1) NOT NULL,
    [AÑO]                        VARCHAR (250) NULL,
    [MES]                        VARCHAR (250) NULL,
    [COMPAÑIA]                   VARCHAR (250) NULL,
    [Country]                    VARCHAR (250) NULL,
    [Shipment_Reference]         VARCHAR (250) NULL,
    [Supplier]                   VARCHAR (350) NULL,
    [Incoterm]                   VARCHAR (250) NULL,
    [Product_Cost]               VARCHAR (250) NULL,
    [Cnt_20_QTY]                 VARCHAR (250) NULL,
    [Cnt_40_QTY]                 VARCHAR (250) NULL,
    [OriginRegion]               VARCHAR (250) NULL,
    [Origin_Country]             VARCHAR (250) NULL,
    [Origin_City_Pick_Up]        VARCHAR (250) NULL,
    [Origin_port_airport_name]   VARCHAR (250) NULL,
    [Dest_Country]               VARCHAR (250) NULL,
    [M3]                         VARCHAR (250) NULL,
    [Freight_forwarder]          VARCHAR (250) NULL,
    [Type]                       VARCHAR (250) NULL,
    [Descripción_Modal]          VARCHAR (250) NULL,
    [Dest_port_airport_name]     VARCHAR (250) NULL,
    [Dest_city]                  VARCHAR (250) NULL,
    [KG]                         VARCHAR (250) NULL,
    [Freight_value]              VARCHAR (250) NULL,
    [Import_Duty]                VARCHAR (250) NULL,
    [Pick_up_date]               VARCHAR (250) NULL,
    [Ship_date]                  VARCHAR (250) NULL,
    [Arrival_date]               VARCHAR (250) NULL,
    [Numeración]                 VARCHAR (250) NULL,
    [Custom_clearance_date]      VARCHAR (250) NULL,
    [Avon_receipt]               VARCHAR (250) NULL,
    [PO]                         VARCHAR (350) NULL,
    [Qty_PO]                     VARCHAR (250) NULL,
    [Product_category]           VARCHAR (250) NULL,
    [Dangerous_goods]            VARCHAR (250) NULL,
    [Spot_shipment]              VARCHAR (250) NULL,
    [International_insurance]    VARCHAR (250) NULL,
    [Customs_expenses]           VARCHAR (250) NULL,
    [Inland_freight_dest]        VARCHAR (250) NULL,
    [Inland_transport_company]   VARCHAR (250) NULL,
    [Doc_Transporte]             VARCHAR (250) NULL,
    [Declaración]                VARCHAR (250) NULL,
    [Referencia]                 VARCHAR (250) NULL,
    [ISD_Factura_Comercial]      VARCHAR (250) NULL,
    [ISD_Gastos_Logisticos]      VARCHAR (250) NULL,
    [Facturas]                   VARCHAR (250) NULL,
    [Fecha_Liquidación]          VARCHAR (250) NULL,
    [Tasa_de_Cambio_Liquidación] VARCHAR (250) NULL,
    [LT_STD]                     VARCHAR (250) NULL
) ON [DATOSMAESTROS];


GO

