CREATE TABLE [maestros].[NS_tblMexico] (
    [Pkid]                          INT            IDENTITY (1, 1) NOT NULL,
    [Año]                           NVARCHAR (250) NULL,
    [IMP/EXP]                       NVARCHAR (250) NULL,
    [MES]                           NVARCHAR (250) NULL,
    [COMPAÑÍA]                      NVARCHAR (250) NULL,
    [CLUSTER]                       NVARCHAR (250) NULL,
    [SHIPMENT REFERENCE]            NVARCHAR (250) NULL,
    [ORIGIN REGION]                 NVARCHAR (250) NULL,
    [ORIGIN COUNTRY]                NVARCHAR (250) NULL,
    [ORIGIN CITY PICK UP]           NVARCHAR (250) NULL,
    [ORIGIN PORT AIRPORT NAME]      NVARCHAR (250) NULL,
    [DESTINATION COUNTRY]           NVARCHAR (250) NULL,
    [DESTINATION CITY]              NVARCHAR (250) NULL,
    [DESTINATION PORT AIRPORT NAME] NVARCHAR (250) NULL,
    [MODAL]                         NVARCHAR (250) NULL,
    [C TYPE]                        NVARCHAR (250) NULL,
    [CNT 20 QTY]                    NVARCHAR (250) NULL,
    [CNT 40 QTY]                    NVARCHAR (250) NULL,
    [GROSS WEIGHT]                  NVARCHAR (250) NULL,
    [M3]                            NVARCHAR (250) NULL,
    [FREIGHT FORWARDER]             NVARCHAR (250) NULL,
    [SUPPLIER]                      NVARCHAR (250) NULL,
    [INCOTERM]                      NVARCHAR (250) NULL,
    [ PRODUCT COST ]                NVARCHAR (250) NULL,
    [ FREIGHT VALUE ]               NVARCHAR (250) NULL,
    [ IMPORT DUTY ]                 NVARCHAR (250) NULL,
    [PICK UP DATE]                  NVARCHAR (250) NULL,
    [SHIP DATE]                     NVARCHAR (250) NULL,
    [ARRIVAL DATE]                  NVARCHAR (250) NULL,
    [CUSTOM CLEARANCE DATE]         NVARCHAR (250) NULL,
    [FECHA ACEPTACIÓN]              NVARCHAR (250) NULL,
    [FECHA RECEPTO]                 NVARCHAR (250) NULL,
    [QTY PO]                        NVARCHAR (250) NULL,
    [PRODUCT CATEGORY]              NVARCHAR (250) NULL,
    [DANGEROUS GOOD]                NVARCHAR (250) NULL,
    [SPOT SHIPMENT]                 NVARCHAR (250) NULL,
    [ INTERNATIONAL INSURANCE ]     NVARCHAR (250) NULL,
    [ CUSTOM EXPENSES ]             NVARCHAR (250) NULL,
    [ INLAND FREIGHT DESP ]         NVARCHAR (250) NULL,
    [INLAND TRANSPORT COMPANY]      NVARCHAR (250) NULL,
    [PEDIMENTO]                     NVARCHAR (250) NULL,
    [FACTURA]                       NVARCHAR (250) NULL,
    [COMENTARIOS]                   NVARCHAR (250) NULL
) ON [DATOSMAESTROS];


GO

